language: python
sudo: required
dist: xenial
matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
#    - python: 3.7
#      env: TOXENV=py37
    - python: 3.4
      env: TOXENV=flake8
    - python: 3.4
      env: TOXENV=pylint
#    - python: 3.4
#      env: TOXENV=coverage
install:
  - pip install tox
script:
  - tox
# - pytest --cov=pystiebeleleltron --cov-report xml
#deploy:
  # https://docs.travis-ci.com/user/deployment/pypi/
  #- provider: pypi
  #  user: fucm
  #  password:
  #    secure: yourencryptedpwhere
  #  distributions: "sdist bdist_wheel"
  #  skip_existing: true
  #  on:
  #    tags: true
