language: python
python:
  - 3.4
  - 3.5
  - 3.6
#script:
# - flake8
# - pytest --cov=pystiebeleleltron --cov-report xml
#deploy:
  # https://docs.travis-ci.com/user/deployment/pypi/
  #- provider: pypi
  #  user: fucm
  #  password:
  #    secure: yourencryptedpwhere
  #  distributions: "sdist bdist_wheel"
  #  skip_existing: true
  #  on:
  #    tags: true
